#!/usr/bin/env python3
"""
Build a navigable "code index" of instructions.md.

Emits docs/blueprint-index.md: every section/sub-section with its number,
title, source line, and a GitHub-style anchor — a fast map from concept to
line number. Complements the semantic index in ../vectordb/.

Run:  python3 tools/build_index.py
"""

from __future__ import annotations

import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "instructions.md"
OUT = ROOT / "docs" / "blueprint-index.md"

HEADER_RE = re.compile(r"^(#{1,3})\s+(.*)$")


def slugify(text: str) -> str:
    """GitHub-flavoured anchor: lowercase, strip accents & punctuation, dash spaces."""
    text = unicodedata.normalize("NFKD", text)
    text = "".join(c for c in text if not unicodedata.combining(c))
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    return re.sub(r"\s+", "-", text.strip())


def main() -> None:
    lines = SOURCE.read_text(encoding="utf-8").splitlines()
    rows: list[str] = []
    counts = {1: 0, 2: 0, 3: 0}
    in_code = False

    for i, line in enumerate(lines, start=1):
        if line.lstrip().startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue
        m = HEADER_RE.match(line)
        if not m:
            continue
        level = len(m.group(1))
        title = m.group(2).strip()
        counts[level] += 1
        indent = "  " * (level - 1)
        anchor = slugify(title)
        rows.append(f"{indent}- **L{i}** · [{title}](../instructions.md#{anchor})")

    header = (
        "# Blueprint Code Index\n\n"
        "> Auto-generated by `tools/build_index.py` — do not edit by hand.\n"
        f"> Source: `instructions.md` ({len(lines)} lines). "
        "For semantic search use `vectordb/query.py`.\n\n"
        f"Sections: {counts[1]} parts · {counts[2]} sections · {counts[3]} sub-sections.\n\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + "\n".join(rows) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} — {sum(counts.values())} entries.")


if __name__ == "__main__":
    main()
